apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consumerdep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: goepjbossacr.azurecr.io/consumer
        env:
        - name: name
          value: "Consumer1"
        - name: queue
          value: "GOEP.TEST"
        - name: camelMqComponent
          value: "jms"
        - name: BROKER_URL
          value: "amqps://jbossasb.servicebus.windows.net?amqp.idleTimeout=120000&jms.receiveLocalOnly=true"
        - name: BROKER_USER
          value: "RootManageSharedAccessKey"
        - name: BROKER_PASSWORD
          value: "cbSusUowdXPq77mjTkpEk4lUuD6zd0xS4EnIIjQ4k+M="



#      restartPolicy: OnFailure