version: "3"
services:
  consumer1:
    image: jms-consumer:latest
    environment:
      # Name of producer (as seen in logs)
      - name=Consumer1

      # Name of queue to consume from
      - queue=GOEP.TEST

      # Number of concurrent consumers in the jvm
      - concurrentConsumers=1

      # Camel component to use for messaging, can be either "jms" or "amqp"
      - camelMqComponent

      # JMS broker url
      - BROKER_URL

      # JMS broker username
      - BROKER_USER

      # JMS broker password
      - BROKER_PASSWORD

  producer1:
    image: jms-producer:latest
    environment:
      # Name of producer (as seen in logs)
      - name=Producer1

      # Name of queue to consume from
      - queue=GOEP.TEST

      # Rate at which messages should be produced (ms)
      - rate=10000

      # Size of message to produce (byte)
      - size=1024

      # Initial delay before first message is produced (ms)
      - delay=0

      # Number of messages to send before stopping (set to 0 for infinity)
      - repeatCount=0

      # Camel component to use for messaging, can be either "jms" or "amqp"
      - camelMqComponent

      # JMS broker url
      - BROKER_URL

      # JMS broker username
      - BROKER_USER

      # JMS broker password
      - BROKER_PASSWORD
