apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: producerdep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: goepjbossacr.azurecr.io/producer
        env:
        - name: name
          value: "Producer1"
        - name: queue
          value: "GOEP.TEST"
        - name: camelMqComponent
          value: "jms"
        - name: BROKER_URL
          value: "amqps://jbossasb.servicebus.windows.net?amqp.idleTimeout=120000&jms.receiveLocalOnly=true"
        - name: BROKER_USER
          value: "RootManageSharedAccessKey"
        - name: BROKER_PASSWORD
          value: "cbSusUowdXPq77mjTkpEk4lUuD6zd0xS4EnIIjQ4k+M="
        - name: size
          value: "1024"
        - name: rate
          value: "10000"
        - name: delay
          value: "0"
#test
#      restartPolicy: OnFailure