---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
name: sftphpa
namespace: sftp
spec:
scaleTargetRef:
  apiVersion: apps/v1beta1
  kind: Deployment
  name: sftphpa
minReplicas: 1
maxReplicas: 3
targetCPUUtilizationPercentage: 50