resources:
- repo: self
queue:
  name: Hosted Linux Preview
variables:
  ACR_NAME: 'goepjbossacr'
steps:
- task: AzureCLI@0
  displayName: 'Build and Push GOEP Base Image for SFTP to ACR'
  inputs:
    azureSubscription: 'Test service connection'

    scriptLocation: inlineScript

    inlineScript: 'az acr build sftp-baseimage --registry $(ACR_NAME) --image  sftp_baseimage  --image sftp_baseimage:{{.Build.ID}}  -f Dockerfile'

## Test